name: Canary Deployment

on:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Install
      run: |
        yarn install
    - name: Build
      run: |
        yarn codegen
    - name: Setup Auth
      run: |
        ./node_modules/.bin/graph auth https://api.thegraph.com/deploy/ ${{ secrets.YANG_STAGING_TOKEN }}
    - name: Deploy Canary
      run: |
        yarn deploy-canary